// TaskBoard
export const ADD_TASKBOARD_SUCCESS = "ADD_TASKBOARD_SUCCESS";
export const UPDATE_COLUMNS = "UPDATE_COLUMNS";
export const EDIT_COLUMN = "EDIT_COLUMN";

// Notebook
export const ADD_NOTEBOOK_SUCCESS = "ADD_NOTEBOOK_SUCCESS";
export const ADD_NOTEBOOK_FAILED = "ADD_NOTEBOOK_FAILED";
export const EDIT_NOTEBOOK_SUCCESS = "EDIT_NOTEBOOK_SUCCESS";
export const EDIT_NOTEBOOK_FAILED = "EDIT_NOTEBOOK_FAILED";
export const DELETE_NOTEBOOK_SUCCESS = "DELETE_NOTEBOOK_SUCCESS";
export const DELETE_NOTEBOOK_FAILED = "DELETE_NOTEBOOK_FAILED";

// Card
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAILED = "ADD_CARD_FAILED";
export const EDIT_CARD_SUCCESS = "EDIT_CARD_SUCCESS";
export const EDIT_CARD_FAILED = "EDIT_CARD_FAILED";
export const DELETE_CARD_SUCCESS = "DELETE_CARD_SUCCESS";
export const DELETE_CARD_FAILED = "DELETE_CARD_FAILED";
export const UPDATE_CARDS = "UPDATE_CARDS";

export const START_ITEM_LOADING = "START_ITEM_LOADING";
export const ITEM_ERROR = "ITEM_ERROR";

// App
export const UPDATE_CURRENT_ITEM = "UPDATE_CURRENT_ITEM";
